In [5]:
import os
import pandas as pd

In [6]:
xlsx=pd.ExcelFile("output.xlsx")


In [7]:
import openpyxl

In [8]:
wb = openpyxl.load_workbook('output.xlsx')
sheet_names=wb.get_sheet_names()
len(sheet_names)

C:\Users\Bryant Tran\Documents\github_desktop\anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated function get_sheet_names (Use wb.sheetnames).
  


23

In [9]:
data1=pd.read_excel(xlsx,"CC96")
data1

Unnamed: 0        Cruise  Month  Year     Date  Quadrant  \
0           0  CalCOFI 9608      8    96  08/1/96        NE   
1           1  CalCOFI 9608      8    96  08/1/96        SE   
2           2  CalCOFI 9608      8    96  08/1/96     Alley   
3           3  CalCOFI 9608      8    96  08/1/96  Offshore   
4           4  CalCOFI 9610     10    96  10/1/96        NE   
5           5  CalCOFI 9610     10    96  10/1/96        SE   
6           6  CalCOFI 9610     10    96  10/1/96     Alley   
7           7  CalCOFI 9610     10    96  10/1/96  Offshore   

   Actinocyclus cf curvatulus   Actinocyclus octanarius   \
0                            0                         0   
1                            0                         0   
2                            0                         0   
3                            0                         0   
4                            0                         0   
5                            0                         0   
6                            0                         0   
7                            0                         0   

   Actinocyclus, undistiguished spp.  Actinoptychus adriaticus + A. vulgaris  \
0                                  0                                       0   
1                                  0                                       0   
2                                  0                                       0   
3                                  0                                       0   
4                                  0                                       0   
5                                  0                                       0   
6                                  0                                       0   
7                                  0                                       0   

   ...  Phaeocystis cf pouchetti  Phaeocystis sp.  Pterosperma cf cuboides  \
0  ...                    1412.3                0                        0   
1  ...                     171.4                0                        0   
2  ...                     816.0                0                        0   
3  ...                       0.0                0                        0   
4  ...                     333.1                0                        0   
5  ...                      16.3                0                        0   
6  ...                       0.0                0                        0   
7  ...                     146.7                0                        0   

   Pterosperma marginatum  Pterosperma pentagonum  Pterosperma cf polygonum   \
0                       0                       0                          0   
1                       0                       0                          0   
2                       0                       0                          0   
3                       0                       0                          0   
4                       0                       0                          0   
5                       0                       0                          0   
6                       0                       0                          0   
7                       0                       0                          0   

   Pterosperma sp. a  undistinguished Pterosperma spp.  \
0                  0                                 0   
1                  0                                 0   
2                  0                                 0   
3                  0                                 0   
4                  0                                 0   
5                  0                                 0   
6                  0                                 0   
7                  0                                 0   

   Richelia intracellularis  SUM MISC. TAXA  
0                         0          1647.7  
1                         0           832.4  
2                         0          2176.0  
3                         0           477.

In [10]:
one=list(data1.columns.values)

In [11]:
data2=pd.read_excel(xlsx,"CC18")
two=list(data2.columns.values)

In [12]:
'Asteromphalus heptactis' in two    

True

In [13]:
data3=pd.read_excel(xlsx,"CC07")
three=list(data3.columns.values)

In [14]:
remove=list(set(two) - set(one))

In [15]:
remove2=list(set(one) - set(two))

In [16]:
remove

['Unnamed: 327',
 4,
 229,
 133,
 295,
 454,
 'Unnamed: 131',
 'Unnamed: 389',
 'Unnamed: 183',
 300,
 621,
 'Unnamed: 309',
 'Unnamed: 383',
 532,
 596,
 218,
 59,
 540]

In [17]:
remove2

['Unnamed: 378',
 'Unnamed: 317',
 'Unnamed: 178',
 'Unnamed: 127',
 'Unnamed: 372',
 'Unnamed: 299']

In [18]:
data1= data1.drop(columns=[col for col in data1 if col in remove2])

In [19]:
data2= data2.drop(columns=[col for col in data2 if col in remove])

In [20]:
#(columns=[col for col in df if col not in final_table_columns])

In [21]:
data3=pd.read_excel(xlsx,"CC97")
len(data3.columns.values)

393

In [22]:
data3= data3.drop(columns=[col for col in data3 if col in remove2])

len(data3.columns.values)

387

In [23]:
data4=pd.read_excel(xlsx,"CC98")
len(data4.columns.values)

393

In [24]:
data4= data4.drop(columns=[col for col in data4 if col in remove2])

len(data4.columns.values)

387

In [25]:
data5=pd.read_excel(xlsx,"CC99")
len(data5.columns.values)

393

In [26]:
data5= data5.drop(columns=[col for col in data5 if col in remove2])

len(data5.columns.values)

387

In [27]:
data6=pd.read_excel(xlsx,"CC00")
len(data6.columns.values)

393

In [28]:
data6= data6.drop(columns=[col for col in data6 if col in remove2])

len(data6.columns.values)

387

In [29]:
data7=pd.read_excel(xlsx,"CC01")
len(data7.columns.values)

393

In [30]:
data7= data7.drop(columns=[col for col in data7 if col in remove2])

len(data7.columns.values)

387

In [31]:
data8=pd.read_excel(xlsx,"CC02")
len(data8.columns.values)

393

In [32]:
data8= data8.drop(columns=[col for col in data8 if col in remove2])

len(data8.columns.values)

387

In [33]:
data9=pd.read_excel(xlsx,"CC03")
len(data9.columns.values)

393

In [34]:
data9= data9.drop(columns=[col for col in data9 if col in remove2])

len(data9.columns.values)

387

In [35]:
data10=pd.read_excel(xlsx,"CC04")
len(data10.columns.values)

393

In [36]:
data10= data10.drop(columns=[col for col in data10 if col in remove2])

len(data10.columns.values)

387

In [37]:
data11=pd.read_excel(xlsx,"CC05")
len(data11.columns.values)

393

In [38]:
data11= data11.drop(columns=[col for col in data11 if col in remove2])

len(data11.columns.values)

387

In [39]:
data12=pd.read_excel(xlsx,"CC06")
len(data12.columns.values)

393

In [40]:
data12= data12.drop(columns=[col for col in data12 if col in remove2])

len(data12.columns.values)

387

In [41]:
data13=pd.read_excel(xlsx,"CC07")
len(data13.columns.values)

393

In [42]:
data13= data13.drop(columns=[col for col in data13 if col in remove2])

len(data13.columns.values)

387

In [43]:
data14=pd.read_excel(xlsx,"CC08")
len(data14.columns.values)

393

In [44]:
data14= data14.drop(columns=[col for col in data14 if col in remove2])

len(data14.columns.values)

387

In [45]:
data15=pd.read_excel(xlsx,"CC09")
len(data15.columns.values)

393

In [46]:
data15= data15.drop(columns=[col for col in data15 if col in remove2])

len(data15.columns.values)

387

In [47]:
data16=pd.read_excel(xlsx,"CC10")
len(data16.columns.values)

393

In [48]:
data16= data16.drop(columns=[col for col in data16 if col in remove2])

len(data16.columns.values)

387

In [49]:
data17=pd.read_excel(xlsx,"CC11")
len(data17.columns.values)

393

In [50]:
data17= data17.drop(columns=[col for col in data17 if col in remove2])

len(data17.columns.values)

387

In [51]:
data18=pd.read_excel(xlsx,"CC12")
len(data18.columns.values)

405

In [52]:
data18= data18.drop(columns=[col for col in data18 if col in remove])

len(data18.columns.values)

387

In [53]:
data19=pd.read_excel(xlsx,"CC13")
len(data19.columns.values)

405

In [54]:
data19= data19.drop(columns=[col for col in data19 if col in remove])

len(data19.columns.values)

387

In [55]:
data20=pd.read_excel(xlsx,"CC14")
len(data20.columns.values)

405

In [56]:
data20= data20.drop(columns=[col for col in data20 if col in remove])

len(data20.columns.values)

387

In [57]:
data21=pd.read_excel(xlsx,"CC15")
len(data21.columns.values)

405

In [58]:
data21= data21.drop(columns=[col for col in data21 if col in remove])

len(data21.columns.values)

387

In [59]:
data22=pd.read_excel(xlsx,"CC16")
len(data22.columns.values)

405

In [60]:
data22= data22.drop(columns=[col for col in data22 if col in remove])

len(data22.columns.values)

387

In [61]:
data23=pd.read_excel(xlsx,"CC17")
len(data23.columns.values)

405

In [62]:
data23= data23.drop(columns=[col for col in data23 if col in remove])

len(data23.columns.values)

387

In [63]:
list(data22.columns.values)==list(data14.columns.values)

False

In [64]:
import numpy as np

In [65]:
c = (np.array(data22.columns.values) == np.array(data4.columns.values))

In [66]:
d = (np.array(data18.columns.values) == np.array(data19.columns.values))

In [72]:
np.where(c==False)

(array([158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183,
        184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196,
        197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
        210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222,
        223, 224, 225, 226, 227, 228, 300, 301, 302, 303, 304, 305, 306,
        307, 308, 309, 310, 369, 370, 374, 375], dtype=int64),)

In [68]:
c

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [69]:
d

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [70]:
np.array(data18.columns.values)[368:374]

array(['SUM COCCOLITHOPHORIDS', 'Dictyocha fibula', 'Dictyocha speculum',
       'Octactis pulchra + O. ocatnaria',
       'undistinguished silicoflagellate spp.', 'SUM SILICOFLAGELLATES'],
      dtype=object)

In [71]:
np.array(data4.columns.values)[368:374]

array(['SUM COCCOLITHOPHORIDS', 'Dictyocha speculum', 'Dictyocha fibula',
       'Octactis pulchra + O. ocatnaria',
       'undistinguished silicoflagellate spp.', 'SUM SILICOFLAGELLATES'],
      dtype=object)

In [ ]:
from pandas import ExcelWriter

In [ ]:
writer = ExcelWriter('final_output.xlsx')
data1.to_excel(writer, 'CC96')
data3.to_excel(writer, 'CC97')
data4.to_excel(writer, 'CC98')
data5.to_excel(writer, 'CC99')
data6.to_excel(writer, 'CC00')
data7.to_excel(writer, 'CC01')
data8.to_excel(writer, 'CC02')
data9.to_excel(writer, 'CC03')
data10.to_excel(writer, 'CC04')
data11.to_excel(writer, 'CC05')
data12.to_excel(writer, 'CC06')
data13.to_excel(writer, 'CC07')
data14.to_excel(writer, 'CC08')
data15.to_excel(writer, 'CC09')
data16.to_excel(writer, 'CC10')
data17.to_excel(writer, 'CC11')
data18.to_excel(writer, 'CC12')
data19.to_excel(writer, 'CC13')
data20.to_excel(writer, 'CC14')
data21.to_excel(writer, 'CC15')
data22.to_excel(writer, 'CC16')
data23.to_excel(writer, 'CC17')
data2.to_excel(writer, 'CC18')
writer.save()
